name: WF Test Integration

on:
  push:
    branchs: ["main"]

permissions:
  id-token: write
  contents: read

jobs:
  ListS3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # install cli
      - uses: unfor19/install-aws-cli-action@v1

      # assume role
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::541128407328:role/role-githubactions
      
      - name: List S3 Buckets
        run: |
          echo "=============>>>>> All S3 Buckets"
          aws s3 ls